import render

REPORT = {
    "provenance": "generated by tests",
    "connections": [
        {
            "id": "C1",
            "move": "Title one. The rest of the move sentence.",
            "sources_involved": ["a", "b"],
            "interpretation": "Interp text.",
            "evidence": [
                {"source_id": "a", "quote": "line one\nline two", "loc": "p.2"},
            ],
            "advances_thesis": "Advances.",
            "tensions": "Strains here.",
            "novelty": 0.5,
            "confidence": 0.6,
            "status": "candidate",
            "scholar_note": "",
        }
    ],
}


def test_render_report_md_shape():
    md = render.render_report_md(REPORT, "demo")
    assert "# Connection report, chapter demo" in md
    assert "## C1. Title one" in md
    assert "**Interpretation.** Interp text." in md
    assert '- a, p.2. "line one line two"' in md
    assert "**Tensions.** Strains here." in md
    assert "Decision: candidate" in md


def test_parse_decisions_round_trip():
    md = render.render_report_md(REPORT, "demo")
    d = render.parse_decisions(md)
    assert d == {"C1": {"decision": "candidate", "note": ""}}


def test_parse_decisions_reads_edits_and_notes():
    md = render.render_report_md(REPORT, "demo").replace(
        "Decision: candidate", "Decision: KEEP\nNote: love this one"
    )
    d = render.parse_decisions(md)
    assert d["C1"]["decision"] == "keep"
    assert d["C1"]["note"] == "love this one"


def test_parse_decisions_handles_scholar_style_report():
    md = (
        "# Connection report, chapter x\n\n"
        "## C2. Ontology is the shared fault line\n\n"
        "stuff\n\nDecision: keep\n\n---\n\n"
        "## C4. The method risks the imposition it studies\n\n"
        "Decision: drop\nNote: This is not a strong connection.\n"
    )
    d = render.parse_decisions(md)
    assert d["C2"]["decision"] == "keep"
    assert d["C4"] == {"decision": "drop", "note": "This is not a strong connection."}
